### ISSUE TITLE
littlefs Specified but spiffs.bin building Platformio

### ISSUE THREAD

**Issue by GerryGit** [IoTManagerProject/IoTManager#64]
This is probably a Platformio issue. I can load your provided bin(firmware and littlefs) files successfully using the Flash Download Tool and spin up the server. When I build the Project myself on PlatformIO  I end up with files firmware.bin and spiffs.bin even though the project platformio.ini specifies board_build.filesystem = littlefs . Is there a plugin, specification general advice or link to dealing with this issue? Thanks for a nice project.

**Comment by GerryGit** [comment]
Or possibly the question is: How to use littlefsbuilder in tools folder?

**Comment by GerryGit** [comment]
Managed to solve this  this by forcing the platform to platform = espressif8266@2.6.0 in platformio.ini then upload from terminal via pio run --target uploadfs. Thanks. Closing.

**Comment by DmitryBorisenko33** [comment]
Hi. Yes correct it is a big problem and sometimes heppened. For me resolving of this problem was add two line in platformio ini: board_build.filesystem = littlefs
extra_scripts = ./tools/littlefsbuilder.py

And after need delete .pio folder to fully clean project.

Also i want to invite you to telegram chat. Theare people from Russia but if you start write english message i will answer you in english. In this chat you can rise any quostions about our firmware and application.

https://t.me/IoTmanager

**Comment by GerryGit** [comment]
Thanks for the invite. I had a look at the group. I think it is easier for me to follow releases on GitHub. It is not really possible for me to follow the posts in Russian. Thanks again.
